/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/favourites/': RouteRecordInfo<'/favourites/', '/favourites', Record<never, never>, Record<never, never>>,
    '/manage/': RouteRecordInfo<'/manage/', '/manage', Record<never, never>, Record<never, never>>,
    '/restaurant/[...]': RouteRecordInfo<'/restaurant/[...]', '/restaurant', Record<never, never>, Record<never, never>>,
    '/restaurant/[id]': RouteRecordInfo<'/restaurant/[id]', '/restaurant/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/restaurants/': RouteRecordInfo<'/restaurants/', '/restaurants', Record<never, never>, Record<never, never>>,
    '/sign-in/': RouteRecordInfo<'/sign-in/', '/sign-in', Record<never, never>, Record<never, never>>,
    '/sign-up/': RouteRecordInfo<'/sign-up/', '/sign-up', Record<never, never>, Record<never, never>>,
  }
}
