/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activeBooking/': RouteRecordInfo<'/activeBooking/', '/activeBooking', Record<never, never>, Record<never, never>>,
    '/bookings/': RouteRecordInfo<'/bookings/', '/bookings', Record<never, never>, Record<never, never>>,
    '/favourites/': RouteRecordInfo<'/favourites/', '/favourites', Record<never, never>, Record<never, never>>,
    '/manage/': RouteRecordInfo<'/manage/', '/manage', Record<never, never>, Record<never, never>>,
    '/manage/bookings/': RouteRecordInfo<'/manage/bookings/', '/manage/bookings', Record<never, never>, Record<never, never>>,
    '/manage/meals/': RouteRecordInfo<'/manage/meals/', '/manage/meals', Record<never, never>, Record<never, never>>,
    '/manage/onboarding/': RouteRecordInfo<'/manage/onboarding/', '/manage/onboarding', Record<never, never>, Record<never, never>>,
    '/manage/reports/': RouteRecordInfo<'/manage/reports/', '/manage/reports', Record<never, never>, Record<never, never>>,
    '/manage/settings/': RouteRecordInfo<'/manage/settings/', '/manage/settings', Record<never, never>, Record<never, never>>,
    '/onboarding/': RouteRecordInfo<'/onboarding/', '/onboarding', Record<never, never>, Record<never, never>>,
    '/restaurant/[...]': RouteRecordInfo<'/restaurant/[...]', '/restaurant', Record<never, never>, Record<never, never>>,
    '/restaurant/[id]': RouteRecordInfo<'/restaurant/[id]', '/restaurant/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/restaurants/': RouteRecordInfo<'/restaurants/', '/restaurants', Record<never, never>, Record<never, never>>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/sign-in/': RouteRecordInfo<'/sign-in/', '/sign-in', Record<never, never>, Record<never, never>>,
    '/sign-up/': RouteRecordInfo<'/sign-up/', '/sign-up', Record<never, never>, Record<never, never>>,
  }
}
