version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - food_postgres_data:/var/lib/postgresql/data
      # - ./path/to/local/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -d ${DATABASE_URL}'"]
      interval: 10s
      timeout: 5s
      retries: 5

#  redis:
#    image: redis:alpine
#    container_name: redis
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    volumes:
#      - food_redis_data:/data

networks:
  default:
    name: food_net

volumes:
  food_postgres_data:
  food_redis_data:
