/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/vue-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query';
import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import { computed, unref } from 'vue';
import type { MaybeRef } from 'vue';
import type { NotFound404Response, UserDTO, Uuid } from '../../api-model';

export const getAdminUsers = (options?: AxiosRequestConfig): Promise<AxiosResponse<UserDTO[]>> => {
  return axios.default.get(`http://localhost:9090/admin/users`, options);
};

export const getGetAdminUsersQueryKey = () => {
  return ['http:', 'localhost:9090', 'admin', 'users'] as const;
};

export const getGetAdminUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminUsers>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUsers>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = getGetAdminUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminUsers>>> = ({ signal }) =>
    getAdminUsers({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminUsers>>,
    TError,
    TData
  >;
};

export type GetAdminUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminUsers>>>;
export type GetAdminUsersQueryError = AxiosError<unknown>;

export const useGetAdminUsers = <
  TData = Awaited<ReturnType<typeof getAdminUsers>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUsers>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAdminUsersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

export const getAdminUsersId = (
  id: MaybeRef<Uuid>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UserDTO>> => {
  id = unref(id);
  return axios.default.get(`http://localhost:9090/admin/users/${id}`, options);
};

export const getGetAdminUsersIdQueryKey = (id: MaybeRef<Uuid>) => {
  return ['http:', 'localhost:9090', 'admin', 'users', id] as const;
};

export const getGetAdminUsersIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminUsersId>>,
  TError = AxiosError<NotFound404Response>,
>(
  id: MaybeRef<Uuid>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUsersId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = getGetAdminUsersIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminUsersId>>> = ({ signal }) =>
    getAdminUsersId(id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getAdminUsersId>>, TError, TData>;
};

export type GetAdminUsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminUsersId>>>;
export type GetAdminUsersIdQueryError = AxiosError<NotFound404Response>;

export const useGetAdminUsersId = <
  TData = Awaited<ReturnType<typeof getAdminUsersId>>,
  TError = AxiosError<NotFound404Response>,
>(
  id: MaybeRef<Uuid>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminUsersId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetAdminUsersIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

export const putAdminUsersId = (
  id: MaybeRef<Uuid>,
  userDTO: MaybeRef<UserDTO>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UserDTO>> => {
  id = unref(id);
  userDTO = unref(userDTO);
  return axios.default.put(`http://localhost:9090/admin/users/${id}`, userDTO, options);
};

export const getPutAdminUsersIdMutationOptions = <
  TError = AxiosError<NotFound404Response | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putAdminUsersId>>,
    TError,
    { id: Uuid; data: UserDTO },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putAdminUsersId>>,
  TError,
  { id: Uuid; data: UserDTO },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putAdminUsersId>>,
    { id: Uuid; data: UserDTO }
  > = (props) => {
    const { id, data } = props ?? {};

    return putAdminUsersId(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutAdminUsersIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putAdminUsersId>>
>;
export type PutAdminUsersIdMutationBody = UserDTO;
export type PutAdminUsersIdMutationError = AxiosError<NotFound404Response | void>;

export const usePutAdminUsersId = <
  TError = AxiosError<NotFound404Response | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putAdminUsersId>>,
    TError,
    { id: Uuid; data: UserDTO },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof putAdminUsersId>>,
  TError,
  { id: Uuid; data: UserDTO },
  TContext
> => {
  const mutationOptions = getPutAdminUsersIdMutationOptions(options);

  return useMutation(mutationOptions);
};
