/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';

export interface AddressDTO {
  addressId: Uuid;
  cityId: string;
  country: string;
  number: string;
  postalCode: string;
  region: string;
  street: string;
}
