/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */

export interface AddressDTO {
  addressId: string;
  city: string;
  country: string;
  /** double */
  latitude: number;
  /** double */
  longitude: number;
  number: string;
  postalCode: string;
  street: string;
}
