/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */

export type BookingStatus = (typeof BookingStatus)[keyof typeof BookingStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookingStatus = {
  Active: 'Active',
  Cancelled: 'Cancelled',
  OutOfDate: 'OutOfDate',
  PickedUp: 'PickedUp',
} as const;
