/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';
import type { Timestamp } from './timestamp';
import type { MealDTO } from './mealDTO';
import type { RestaurantDTO } from './restaurantDTO';
import type { BookingStatus } from './bookingStatus';

export interface BookingDTO {
  bookingId: Uuid;
  deadlinePickUpTimestamp: Timestamp;
  meal: MealDTO;
  orderedTimestamp: Timestamp;
  pickedUpTimestamp: Timestamp;
  restaurant: RestaurantDTO;
  status: BookingStatus;
  userId: Uuid;
}
