/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Timestamp } from './timestamp';
import type { Uuid } from './uuid';

export interface BookingDTO {
  deadlinePickUpTimestamp: Timestamp;
  id: Uuid;
  mealId: Uuid;
  orderedTimestamp: Timestamp;
  pickedUpTimestamp: Timestamp;
  userId: Uuid;
}
