/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';

export interface DeleteFavouriteRestaurantsDTO {
  restaurant_ids: Uuid[];
  user_id: Uuid;
}
