/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';

export type GetBookingsParams = {
  /**
   * If exists, returns booking by userId, eg. /bookings?userId=123
   */
  userId?: Uuid;
  /**
   * If exists, returns all bookings for restaurant
   */
  restaurantId?: Uuid;
  /**
   * Syntax: restaurantId + active - returns all pending bookings for restaurant
   */
  active?: Uuid;
};
