/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';

export type GetGeoAutocompleteParams = {
  /**
   * Partial city/street query, such as "War", "Warsz" or "Warszawa"
   */
  query: string;
  /**
   * See: https://developers.google.com/maps/documentation/places/web-service/session-tokens
   */
  sessionToken: Uuid;
};
