/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */

export interface HoursDTO {
  friday: string[];
  monday: string[];
  saturday: string[];
  sunday: string[];
  thursday: string[];
  tuesday: string[];
  wednesday: string[];
}
