/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';

export interface MealDTO {
  description: string;
  id: Uuid;
  name: string;
  restaurant_id: Uuid;
}
