/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { HttpException } from './httpException';

/**
 * Not found
 */
export type NotFound404Response = HttpException;
