/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */

export type PostUsersUserIdAddressParams = {
  /**
   * Place ID from Google Maps API
   */
  placeId: string;
};
