/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */

export interface ProblemDetail {
  detail?: string;
  instance?: string;
  status?: number;
  title?: string;
  type?: string;
}
