/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */

export type PutAdminReportsRestaurantsIdParams = {
  /**
 * true = ban user associated with reportId (path variable) and close report
false = close report
 */
  ban: boolean;
};
