/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';

export interface ReportsInputDTO {
  cause: string;
  restaurant_id: Uuid;
  user_id: Uuid;
}
