/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';

export interface RestaurantInputDTO {
  address_id?: Uuid;
  name?: string;
  phoneNumber?: string;
  user_id?: Uuid;
}
