/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';

export interface RestaurantDTO {
  addressId: Uuid;
  id: Uuid;
  imageUrl?: string;
  isActive: boolean;
  name: string;
  phoneNumber: string;
  userId: Uuid;
}
