/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { AddressInputDto } from './addressInputDto';
import type { Uuid } from './uuid';

export interface RestaurantInputDTO {
  addressInputDto: AddressInputDto;
  name?: string;
  phoneNumber?: string;
  userId?: Uuid;
}
