/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */

export type RestaurantDTOStatus = (typeof RestaurantDTOStatus)[keyof typeof RestaurantDTOStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RestaurantDTOStatus = {
  Banned: 'Banned',
  Active: 'Active',
  Inactive: 'Inactive',
} as const;
