/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */

export type RestaurantStatus = (typeof RestaurantStatus)[keyof typeof RestaurantStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RestaurantStatus = {
  Banned: 'Banned',
  Active: 'Active',
  Inactive: 'Inactive',
} as const;
