/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Uuid } from './uuid';
import type { Role } from './role';

/**
 * User object.
 */
export interface UserDTO {
  email: string;
  firstName: string;
  id: Uuid;
  isBlocked: boolean;
  password: string;
  phoneNumber: string;
  role: Role;
  secondName: string;
  username: string;
}
