/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { AddressDTO } from './addressDTO';
import type { Uuid } from './uuid';
import type { Role } from './role';

export interface UserMeDTO {
  address?: AddressDTO;
  email: string;
  firstName: string;
  id: Uuid;
  phoneNumber: string;
  role: Role;
  secondName: string;
  username: string;
}
