/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { Role } from './role';

/**
 * User object.
 */
export interface UserInputDTO {
  email: string;
  firstName: string;
  password: string;
  phoneNumber: string;
  role: Role;
  secondName: string;
  username: string;
}
