/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { CityDTO } from './cityDTO';
import type { Role } from './role';
import type { Uuid } from './uuid';

export interface UserMeDTO {
  city?: CityDTO;
  email: string;
  firstName: string;
  phoneNumber: string;
  role: Role;
  secondName: string;
  userMeId: Uuid;
  username: string;
}
