/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sumatywny
 * OpenAPI spec version: 1.0.0
 */
import type { HttpException } from './httpException';

/**
 * Validation failed
 */
export type ValidationFailed422Response = HttpException;
